"$schema" = "https://starship.rs/config-schema.json"

command_timeout = 1200
scan_timeout = 50
palette = "poimandres"

format = """
$directory$git_branch$git_status$git_metrics$python$rust$golang
$character"""

right_format = """$cmd_duration"""

[palettes.poimandres]
bright-yellow = "#fffac2"
bright-mint = "#5de4c7"
lower-mint = "#5fb3a1"
blueish-green = "#42675a"

lower-blue = "#89ddff"
light-blue = "#add7ff"
desaturated-blue = "#91b4d5"
bluishGray-brighter = "#7390aa"

hot-red = "#d0679d"
pink = "#f087bd"
gray = "#a6accd"

# darker-gray = "#767c9d"
# bluish-gray = "#506477"
# selection = "#30354b"
# focus = "#303340"
# bg = "#1b1e28"

off-white = "#e4f0fb"

white = "#ffffff"
# black = '#000000'

# Storm overrides
darker-gray = "#868cad"
bluish-gray = "#607487"
selection = "#33394a"
focus = "#404350"
bg = "#252b37"
black = "#101010"

[character]
success_symbol = "[❯](bold lower-mint)"
error_symbol = "[❯](bold hot-red)"
vicmd_symbol = "[↔](bold bright-yellow)"

[battery]
disabled = true

[cmd_duration]
min_time = 1200
format = "⏱ [$duration]($style) "
style = "bold bright-yellow"

[directory]
format = "[](bg:focus fg:bright-mint)[ $path ](bg:focus fg:white)[](fg:focus)"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[](bg:selection fg:focus)[ $branch ](bg:selection fg:lower-blue)[](fg:selection)"

[git_metrics]
disabled = false
added_style = "bright-mint"
deleted_style = "hot-red"

[git_status]
style = "gray"
format = '([\[$all_status$ahead_behind\]]($style) )'

[package]
disabled = true

[lua]
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"
symbol = '🐍 '
pyenv_version_name = true
python_binary = ["py"]
detect_folders = [".python-version", "pyproject.toml"]

[rust]
format = "[$symbol$version]($style) "
symbol = '🦀 '
style = "bold red"

[nodejs]
symbol = " "
style = "bold green"
format = "[$symbol$version]($style) "
detect_files = ["package.json", ".node-version", ".nvmrc"]
detect_extensions = ["js", "ts", "mjs", "cjs"]

[custom.angular]
when = ''' test -f package.json && grep -q '"@angular/core"' package.json '''
command = ''' node -e "try{const p=require('./package.json');const v=(p.dependencies?.['@angular/core']||p.devDependencies?.['@angular/core']||'').replace(/^[^0-9]*/, ''); if(v) console.log('🅰 '+v)}catch(e){}" '''
style = "bold red"
format = "[$output]($style) "
